apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/olqs/applications'
      revision: main           # oder z.B. main
      # Finde jede application.yaml, egal in welchem Unterordner
      files:
      - path: '**/application.yaml'
  template:
    metadata:
      name: '{{path.basename}}-meta'
      namespace: argocd
    spec:
      project: default

      source:
        repoURL: 'https://github.com/olqs/applications'
        targetRevision: main
        # Pfad zum Ordner, in dem sich die application.yaml befindet
        path: '{{path.basename}}'

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true        # lösche Ressourcen, die nicht mehr im Git sind
          selfHeal: true     # stelle bei manuellen Änderungen den Git-Zustand wieder her

